name = "plex_pin_auth"
version = "1.0.0"
gleam = ">= 1.1.0"
target = "erlang"

description = "Authenticate with Plex via the Plex pin authentication method"
licences = ["MIT"]
repository = { type = "github", user = "harrisonhoward", repo = "plex_pin_auth" }
links = [
    { title = "Related Project", href = "https://github.com/harrisonhoward/plex_discord_rpc" },
]

internal_modules = ["plex_pin_auth/internal", "plex_pin_auth/internal/*"]

[dependencies]
gleam_stdlib = "~> 0.36"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_hackney = ">= 1.2.0 and < 2.0.0"
gleam_json = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
